### ISSUE TITLE
DB::Exception: Table default.events doesn't exist

### ISSUE THREAD

**Issue by fdaugs** [PostHog/postgres-plugin#6]
When I start an export of historical data I get the following error:

```
Error: Code: 60. DB::Exception: Table default.events doesn't exist. (UNKNOWN_TABLE) (version 22.3.15.33 (official build))

    at parseError (/code/plugin-server/node_modules/@posthog/clickhouse/src/parse-error.js:2:15)
    at errorHandler (/code/plugin-server/node_modules/@posthog/clickhouse/src/clickhouse.js:27:13)
    at IncomingMessage.<anonymous> (/code/plugin-server/node_modules/@posthog/clickhouse/src/clickhouse.js:95:11)
    at IncomingMessage.emit (node:events:525:35)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

**Comment by xvello** [comment]
Closing as this plugin has been deprecated in favor of our [Postgres destination for batch exports](https://posthog.com/docs/cdp/batch-exports/postgres).
